### ISSUE TITLE
Replace tree-sitter submodules with Rust bindings

### ISSUE THREAD

**Issue by Luni-4** [mozilla/rust-code-analysis#442]
Some of the `tree-sitter` grammars can be used as `Cargo.toml` dependencies. In this way, some submodules can be removed.

Pros
- A cleaner repository
- Avoid breaks during the update of a tree-sitter grammar due to some problems in handling submodules
- Less options and commands to clone the project

Cons 
- Impossibility to change the grammars directly in this repo, the grammars have to be modified upstream

Submodules languages:

- [x] tree-sitter-java (#449)
- [x] tree-sitter-python (#464)
- [x] tree-sitter-cpp (#498)
- [x] tree-sitter-rust (#594)
- [x] tree-sitter-javascript (#463)
- [x] tree-sitter-typescript (#592)

**Comment by marco-c** [comment]
I've removed it from the "API & User Interface" project since this is not affecting end users of the project, but only people who want to build it.
